// Alexander Campaign Layer data.
// Hand-curated v0.1 scaffold: narrative stops + generalized route segments.
// Coordinates are intentionally approximate where the ancient location or route
// is disputed. Do not treat route polylines as surveyed ancient roads.

const ALEXANDER_PHASES = {
  macedon: {
    label: 'Macedon',
    years: '356-334 BC',
    color: '#8f6f3f',
    summary: 'Origins, succession, and preparation for the Asian campaign.',
  },
  anatolia: {
    label: 'Asia Minor',
    years: '334-333 BC',
    color: '#7b6fb3',
    summary: 'Crossing into Asia and breaking Persian control in western Anatolia.',
  },
  levantEgypt: {
    label: 'Levant and Egypt',
    years: '333-331 BC',
    color: '#3f8f88',
    summary: 'Securing the eastern Mediterranean before turning inland against Darius.',
  },
  persianCore: {
    label: 'Persian Core',
    years: '331-330 BC',
    color: '#b07848',
    summary: 'Gaugamela, the imperial capitals, and the symbolic end of Achaemenid power.',
  },
  eastIndia: {
    label: 'East and India',
    years: '329-326 BC',
    color: '#5e8b4f',
    summary: 'Bactria, Sogdiana, and the final eastward push into the Indus world.',
  },
  returnDeath: {
    label: 'Return and Death',
    years: '325-323 BC',
    color: '#8c5b5b',
    summary: "The hard return west, army crisis, and Alexander's death at Babylon.",
  },
};

const ALEXANDER_STOPS = [
  {
    id: 'pella',
    name: 'Pella',
    modern: 'Pella, Greece',
    lat: 40.761,
    lng: 22.519,
    year: -356,
    year_label: '356 BC',
    phase: 'macedon',
    type: 'origin',
    certainty: 'secure',
    desc: 'Traditional birthplace of Alexander and the royal center of Argead Macedon.',
    significance: 'Sets the campaign in a Macedonian, not Athenian or generic Greek, power base.',
    ancient_sources: ['Plutarch, Alexander 3'],
    source_note: '',
  },
  {
    id: 'aegae',
    name: 'Aegae',
    modern: 'Vergina, Greece',
    lat: 40.486,
    lng: 22.318,
    year: -336,
    year_label: '336 BC',
    phase: 'macedon',
    type: 'capital',
    certainty: 'secure',
    desc: 'Philip II is assassinated at Aegae and Alexander succeeds to the Macedonian throne.',
    significance: 'The Asian campaign begins as an inherited royal project that Alexander rapidly makes his own.',
    ancient_sources: ['Diodorus 16.91-94'],
    source_note: '',
  },
  {
    id: 'amphipolis',
    name: 'Amphipolis',
    modern: 'Amfipoli, Greece',
    lat: 40.823,
    lng: 23.847,
    year: -334,
    year_label: '334 BC',
    phase: 'macedon',
    type: 'muster',
    certainty: 'secure',
    desc: 'A major Macedonian base near the Strymon, useful for staging movement toward the Hellespont.',
    significance: 'Represents the logistical hinge between Macedon and the crossing into Asia.',
    ancient_sources: ['Arrian 1.11'],
    source_note: '',
  },
  {
    id: 'hellespont-crossing',
    name: 'Hellespont Crossing',
    modern: 'Dardanelles, Turkey',
    lat: 40.205,
    lng: 26.405,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'crossing',
    certainty: 'approximate',
    desc: 'Alexander crosses from Europe into Asia at the Hellespont.',
    significance: 'The crossing transforms a Macedonian succession into a campaign against the Persian Empire.',
    ancient_sources: ['Arrian 1.11'],
    source_note: 'Marker represents the crossing zone, not an exact embarkation point.',
  },
  {
    id: 'ilion',
    name: 'Ilion / Troy',
    modern: 'Hisarlik, Turkey',
    lat: 39.957,
    lng: 26.239,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'ritual',
    certainty: 'secure',
    desc: 'Alexander visits Ilion and frames the campaign through Homeric memory.',
    significance: 'Makes the expedition legible as mythic revenge and heroic succession, not only strategy.',
    ancient_sources: ['Arrian 1.11-12'],
    source_note: '',
  },
  {
    id: 'granicus',
    name: 'Granicus River',
    modern: 'Biga River, Turkey',
    lat: 40.263,
    lng: 27.193,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'battle',
    certainty: 'approximate',
    desc: 'Alexander defeats Persian satrapal forces at the first major battle of the Asian campaign.',
    significance: 'Opens western Anatolia and proves the Macedonian army can win on Persian ground.',
    ancient_sources: ['Arrian 1.13-16'],
    source_note: 'Battlefield placement along the river is approximate.',
  },
  {
    id: 'sardis',
    name: 'Sardis',
    modern: 'Sart, Turkey',
    lat: 38.488,
    lng: 28.040,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'capital',
    certainty: 'secure',
    desc: 'The Lydian capital and Persian administrative center surrenders to Alexander.',
    significance: 'Gives Alexander a major western Anatolian power center without a long siege.',
    ancient_sources: ['Arrian 1.17'],
    source_note: '',
  },
  {
    id: 'miletus',
    name: 'Miletus',
    modern: 'Balat, Turkey',
    lat: 37.530,
    lng: 27.278,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'siege',
    certainty: 'secure',
    desc: 'Alexander takes Miletus and makes a consequential decision to neutralize Persian naval power from land.',
    significance: 'Shows the campaign strategy: capture ports rather than fight Persia ship-for-ship.',
    ancient_sources: ['Arrian 1.18-19'],
    source_note: '',
  },
  {
    id: 'halicarnassus',
    name: 'Halicarnassus',
    modern: 'Bodrum, Turkey',
    lat: 37.038,
    lng: 27.430,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'siege',
    certainty: 'secure',
    desc: 'A hard siege against strong Persian-aligned resistance on the Carian coast.',
    significance: 'Marks the last major western Anatolian coastal resistance before Alexander turns inland.',
    ancient_sources: ['Arrian 1.20-23'],
    source_note: '',
  },
  {
    id: 'gordium',
    name: 'Gordium',
    modern: 'Yassihoyuk, Turkey',
    lat: 39.654,
    lng: 31.999,
    year: -333,
    year_label: '333 BC',
    phase: 'anatolia',
    type: 'symbol',
    certainty: 'secure',
    desc: 'Alexander reaches the old Phrygian capital associated with the Gordian knot tradition.',
    significance: 'Turns a logistical stop into a famous claim of destined rule over Asia.',
    ancient_sources: ['Arrian 2.3'],
    source_note: '',
  },
  {
    id: 'tarsus',
    name: 'Tarsus',
    modern: 'Tarsus, Turkey',
    lat: 36.917,
    lng: 34.895,
    year: -333,
    year_label: '333 BC',
    phase: 'anatolia',
    type: 'city',
    certainty: 'secure',
    desc: 'Alexander passes through Cilicia before the campaign turns toward the Syrian Gates and Issus.',
    significance: 'A geographic hinge from Anatolia into the Levantine theater.',
    ancient_sources: ['Arrian 2.4'],
    source_note: '',
  },
  {
    id: 'issus',
    name: 'Issus',
    modern: 'near Dörtyol, Turkey',
    lat: 36.86,
    lng: 36.20,
    year: -333,
    year_label: '333 BC',
    phase: 'levantEgypt',
    type: 'battle',
    certainty: 'approximate',
    desc: 'Alexander defeats Darius III in a constrained battlefield near the Gulf of Issus.',
    significance: 'Darius flees, the Persian royal family is captured, and the war becomes personal.',
    ancient_sources: ['Arrian 2.6-12'],
    source_note: 'The exact battlefield and river identification are debated.',
  },
  {
    id: 'tyre',
    name: 'Tyre',
    modern: 'Sour, Lebanon',
    lat: 33.270,
    lng: 35.204,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'siege',
    certainty: 'secure',
    desc: 'Alexander besieges and takes the island city of Tyre after building a causeway.',
    significance: 'Secures the Phoenician coast and undermines Persian naval reach.',
    ancient_sources: ['Arrian 2.15-24'],
    source_note: '',
  },
  {
    id: 'gaza',
    name: 'Gaza',
    modern: 'Gaza',
    lat: 31.505,
    lng: 34.462,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'siege',
    certainty: 'approximate',
    desc: 'A difficult siege blocks the route from the Levant into Egypt.',
    significance: 'The last major fortified obstacle before the Egyptian phase.',
    ancient_sources: ['Arrian 2.25-27'],
    source_note: 'Marker indicates the ancient city area in a heavily transformed modern urban landscape.',
  },
  {
    id: 'memphis',
    name: 'Memphis',
    modern: 'Mit Rahina, Egypt',
    lat: 29.849,
    lng: 31.254,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'capital',
    certainty: 'secure',
    desc: 'Alexander enters Egypt and is received at Memphis.',
    significance: 'Egypt becomes a prestige theater where conquest, kingship, and divine legitimacy converge.',
    ancient_sources: ['Arrian 3.1'],
    source_note: '',
  },
  {
    id: 'alexandria-egypt',
    name: 'Alexandria',
    modern: 'Alexandria, Egypt',
    lat: 31.200,
    lng: 29.918,
    year: -331,
    year_label: '331 BC',
    phase: 'levantEgypt',
    type: 'foundation',
    certainty: 'secure',
    desc: 'Alexander founds the city that becomes the most famous Alexandria.',
    significance: 'A durable urban legacy outlasting the campaign itself.',
    ancient_sources: ['Arrian 3.1-2'],
    source_note: '',
  },
  {
    id: 'siwa',
    name: 'Siwa Oasis',
    modern: 'Siwa, Egypt',
    lat: 29.204,
    lng: 25.519,
    year: -331,
    year_label: '331 BC',
    phase: 'levantEgypt',
    type: 'oracle',
    certainty: 'secure',
    desc: 'Alexander visits the oracle of Ammon in the Western Desert.',
    significance: "The episode becomes central to traditions about Alexander's divine status.",
    ancient_sources: ['Arrian 3.3-4', 'Plutarch, Alexander 27'],
    source_note: '',
  },
  {
    id: 'gaugamela',
    name: 'Gaugamela',
    modern: 'near Mosul, Iraq',
    lat: 36.360,
    lng: 43.250,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'battle',
    certainty: 'disputed',
    desc: 'Alexander defeats Darius III in the decisive open battle for the Persian Empire.',
    significance: 'The victory opens Babylon, Susa, and Persepolis and effectively ends Achaemenid imperial control.',
    ancient_sources: ['Arrian 3.8-15'],
    source_note: 'The battlefield location is approximate and debated.',
  },
  {
    id: 'babylon-entry',
    name: 'Babylon',
    modern: 'Hillah, Iraq',
    lat: 32.542,
    lng: 44.421,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: 'Alexander enters Babylon after Gaugamela.',
    significance: "Achaemenid imperial geography becomes Alexander's own administrative stage.",
    ancient_sources: ['Arrian 3.16'],
    source_note: '',
  },
  {
    id: 'susa',
    name: 'Susa',
    modern: 'Shush, Iran',
    lat: 32.189,
    lng: 48.257,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: 'Alexander takes Susa and its treasury.',
    significance: 'Control of the imperial treasuries turns conquest into durable command.',
    ancient_sources: ['Arrian 3.16'],
    source_note: '',
  },
  {
    id: 'persian-gate',
    name: 'Persian Gate',
    modern: 'Zagros Mountains, Iran',
    lat: 30.72,
    lng: 51.55,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'battle',
    certainty: 'approximate',
    desc: 'Persian forces resist Alexander in the mountain approaches to Persis.',
    significance: 'Shows conquest still required brutal local passage even after Gaugamela.',
    ancient_sources: ['Arrian 3.18'],
    source_note: 'Marker is a generalized location for the mountain pass battle.',
  },
  {
    id: 'persepolis',
    name: 'Persepolis',
    modern: 'Marvdasht, Iran',
    lat: 29.935,
    lng: 52.891,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: 'Alexander occupies Persepolis and later burns the palace complex.',
    significance: 'The most symbolically charged moment in the overthrow of Persian royal power.',
    ancient_sources: ['Arrian 3.18', 'Diodorus 17.70-72'],
    source_note: '',
  },
  {
    id: 'ecbatana',
    name: 'Ecbatana',
    modern: 'Hamadan, Iran',
    lat: 34.799,
    lng: 48.514,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: 'Alexander reaches the Median capital while pursuing Darius and reorganizing the campaign.',
    significance: 'Marks the transition from conquering the Persian core to chasing power eastward.',
    ancient_sources: ['Arrian 3.19'],
    source_note: '',
  },
  {
    id: 'bactra',
    name: 'Bactra',
    modern: 'Balkh, Afghanistan',
    lat: 36.758,
    lng: 66.898,
    year: -329,
    year_label: '329 BC',
    phase: 'eastIndia',
    type: 'capital',
    certainty: 'secure',
    desc: "Bactra becomes a major base in Alexander's Central Asian campaigns.",
    significance: 'The campaign changes from imperial takeover to frontier war and consolidation.',
    ancient_sources: ['Arrian 3.28-29'],
    source_note: '',
  },
  {
    id: 'sogdian-rock',
    name: 'Sogdian Rock',
    modern: 'Sogdiana, Uzbekistan/Tajikistan region',
    lat: 38.55,
    lng: 67.00,
    year: -327,
    year_label: '327 BC',
    phase: 'eastIndia',
    type: 'siege',
    certainty: 'disputed',
    desc: 'Alexander captures a mountain stronghold associated with Sogdian resistance.',
    significance: "The episode is tied to the eastern resistance and Alexander's marriage to Roxane.",
    ancient_sources: ['Arrian 4.18-19'],
    source_note: 'The exact location of the Sogdian Rock is disputed; marker is regional.',
  },
  {
    id: 'taxila',
    name: 'Taxila',
    modern: 'Taxila, Pakistan',
    lat: 33.746,
    lng: 72.839,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'city',
    certainty: 'secure',
    desc: 'Taxila receives Alexander and becomes a diplomatic gateway into the Indus world.',
    significance: 'Shows conquest by alliance as much as by battle at the edge of the known campaign world.',
    ancient_sources: ['Arrian 5.3-8'],
    source_note: '',
  },
  {
    id: 'hydaspes',
    name: 'Hydaspes',
    modern: 'Jhelum River, Pakistan',
    lat: 32.93,
    lng: 73.73,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'battle',
    certainty: 'approximate',
    desc: 'Alexander fights Porus near the Hydaspes River.',
    significance: "The last great pitched battle of Alexander's eastward advance.",
    ancient_sources: ['Arrian 5.9-19'],
    source_note: 'Battlefield placement along the Jhelum/Hydaspes is approximate.',
  },
  {
    id: 'hyphasis',
    name: 'Hyphasis',
    modern: 'Beas River, India',
    lat: 31.82,
    lng: 75.12,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'turning-point',
    certainty: 'approximate',
    desc: "Alexander's army refuses to continue farther east at the Hyphasis.",
    significance: 'The limit of conquest is set by the army, not by an enemy battlefield defeat.',
    ancient_sources: ['Arrian 5.25-29'],
    source_note: 'Marker represents the Beas/Hyphasis turnback zone.',
  },
  {
    id: 'gedrosian-route',
    name: 'Gedrosian Route',
    modern: 'Makran / Balochistan',
    lat: 26.3,
    lng: 64.0,
    year: -325,
    year_label: '325 BC',
    phase: 'returnDeath',
    type: 'march',
    certainty: 'uncertain',
    desc: 'Part of the army returns west through the harsh Gedrosian desert region.',
    significance: 'The catastrophic return exposes the human cost of the eastern expedition.',
    ancient_sources: ['Arrian 6.22-27'],
    source_note: 'Marker and route are highly generalized; the exact march path is debated.',
  },
  {
    id: 'pasargadae',
    name: 'Pasargadae',
    modern: 'near Saadat Shahr, Iran',
    lat: 30.194,
    lng: 53.179,
    year: -324,
    year_label: '324 BC',
    phase: 'returnDeath',
    type: 'royal-site',
    certainty: 'secure',
    desc: 'Alexander returns to the Persian royal landscape associated with Cyrus.',
    significance: "Highlights Alexander's attempt to inhabit, restore, and control Achaemenid kingship.",
    ancient_sources: ['Arrian 6.29'],
    source_note: '',
  },
  {
    id: 'opis',
    name: 'Opis',
    modern: 'near Baghdad, Iraq',
    lat: 33.45,
    lng: 44.65,
    year: -324,
    year_label: '324 BC',
    phase: 'returnDeath',
    type: 'mutiny',
    certainty: 'approximate',
    desc: 'Alexander confronts a major army crisis at Opis.',
    significance: "The campaign's human and political strain comes into the open before the final return to Babylon.",
    ancient_sources: ['Arrian 7.8-12'],
    source_note: 'The exact location of ancient Opis is uncertain.',
  },
  {
    id: 'babylon-death',
    name: 'Babylon - Death of Alexander',
    modern: 'Hillah, Iraq',
    lat: 32.542,
    lng: 44.421,
    year: -323,
    year_label: '323 BC',
    phase: 'returnDeath',
    type: 'death',
    certainty: 'secure',
    desc: 'Alexander dies at Babylon at age 32.',
    significance: 'The lifetime campaign ends and the political problem of succession begins.',
    ancient_sources: ['Arrian 7.24-27', 'Plutarch, Alexander 75-77'],
    source_note: '',
  },
];

const ALEXANDER_ROUTES = [
  { id: 'pella-aegae-amphipolis', from: 'pella', to: 'amphipolis', phase: 'macedon', certainty: 'reconstructed', label: 'Macedonian base route', coords: [[22.519, 40.761], [22.318, 40.486], [23.847, 40.823]], source_note: 'Narrative connector between Macedonian royal centers and the eastward staging area.' },
  { id: 'amphipolis-hellespont', from: 'amphipolis', to: 'hellespont-crossing', phase: 'anatolia', certainty: 'reconstructed', label: 'Toward the Hellespont', coords: [[23.847, 40.823], [24.40, 40.86], [25.55, 40.45], [26.405, 40.205]], source_note: 'Generalized overland approach to the crossing.' },
  { id: 'hellespont-granicus-sardis', from: 'hellespont-crossing', to: 'sardis', phase: 'anatolia', certainty: 'reconstructed', label: 'Opening of Asia Minor', coords: [[26.405, 40.205], [26.239, 39.957], [27.193, 40.263], [28.040, 38.488]], source_note: 'Generalized route through northwest Anatolia after the crossing.' },
  { id: 'sardis-coast-halicar-gordium', from: 'sardis', to: 'gordium', phase: 'anatolia', certainty: 'reconstructed', label: 'Coastal sieges and inland turn', coords: [[28.040, 38.488], [27.278, 37.530], [27.430, 37.038], [30.70, 37.75], [31.999, 39.654]], source_note: 'Simplifies a campaign sequence with coastal and inland movements.' },
  { id: 'gordium-tarsus-issus', from: 'gordium', to: 'issus', phase: 'anatolia', certainty: 'reconstructed', label: 'Through Cilicia to Issus', coords: [[31.999, 39.654], [33.00, 38.60], [34.895, 36.917], [36.20, 36.86]], source_note: 'Generalized movement from central Anatolia through Cilicia.' },
  { id: 'issus-tyre-gaza', from: 'issus', to: 'gaza', phase: 'levantEgypt', certainty: 'reconstructed', label: 'Down the Levantine coast', coords: [[36.20, 36.86], [35.90, 35.50], [35.52, 34.45], [35.204, 33.270], [34.462, 31.505]], source_note: 'Narrative coastal connector, not a surveyed itinerary.' },
  { id: 'gaza-memphis-alexandria-siwa', from: 'gaza', to: 'siwa', phase: 'levantEgypt', certainty: 'reconstructed', label: 'Egypt and the oracle', coords: [[34.462, 31.505], [31.254, 29.849], [29.918, 31.200], [27.50, 30.50], [25.519, 29.204]], source_note: 'Generalized Egyptian route, including the desert journey to Siwa.' },
  { id: 'egypt-gaugamela-babylon', from: 'siwa', to: 'babylon-entry', phase: 'persianCore', certainty: 'reconstructed', label: 'Return east to Gaugamela and Babylon', coords: [[25.519, 29.204], [29.918, 31.200], [34.462, 31.505], [36.20, 36.86], [43.250, 36.360], [44.421, 32.542]], source_note: 'Compresses the return from Egypt and the march to Gaugamela into a narrative connector.' },
  { id: 'babylon-susa-persepolis-ecbatana', from: 'babylon-entry', to: 'ecbatana', phase: 'persianCore', certainty: 'reconstructed', label: 'Imperial capitals', coords: [[44.421, 32.542], [48.257, 32.189], [51.55, 30.72], [52.891, 29.935], [48.514, 34.799]], source_note: 'Generalized route across the Persian imperial core.' },
  { id: 'ecbatana-bactra-sogdian', from: 'ecbatana', to: 'sogdian-rock', phase: 'eastIndia', certainty: 'uncertain', label: 'Pursuit and eastern campaigns', coords: [[48.514, 34.799], [54.35, 36.70], [61.20, 36.70], [66.898, 36.758], [67.00, 38.55]], source_note: 'Highly simplified eastward route; many exact movements are omitted.' },
  { id: 'sogdian-taxila-hydaspes-hyphasis', from: 'sogdian-rock', to: 'hyphasis', phase: 'eastIndia', certainty: 'reconstructed', label: 'Into the Indus world', coords: [[67.00, 38.55], [69.20, 34.55], [72.839, 33.746], [73.73, 32.93], [75.12, 31.82]], source_note: 'Generalized connector from Central Asia into the Punjab.' },
  { id: 'hyphasis-gedrosia-pasargadae-opis-babylon', from: 'hyphasis', to: 'babylon-death', phase: 'returnDeath', certainty: 'uncertain', label: 'Return west', coords: [[75.12, 31.82], [68.35, 25.40], [64.0, 26.3], [58.0, 27.5], [53.179, 30.194], [44.65, 33.45], [44.421, 32.542]], source_note: 'The Gedrosian return is deliberately generalized and should be shown as uncertain.' },
];
