// Alexander Campaign Layer data.
// Hand-curated v0.1 scaffold: narrative stops + generalized route segments.
// Coordinates are intentionally approximate where the ancient location or route
// is disputed. Do not treat route polylines as surveyed ancient roads.

const ALEXANDER_PHASES = {
  macedon: {
    label: 'Macedon',
    years: '356-334 BC',
    color: '#8f6f3f',
    summary: 'Origins, succession, and preparation for the Asian campaign.',
  },
  anatolia: {
    label: 'Asia Minor',
    years: '334-333 BC',
    color: '#7b6fb3',
    summary: 'Crossing into Asia and breaking Persian control in western Anatolia.',
  },
  levantEgypt: {
    label: 'Levant and Egypt',
    years: '333-331 BC',
    color: '#3f8f88',
    summary: 'Securing the eastern Mediterranean before turning inland against Darius.',
  },
  persianCore: {
    label: 'Persian Core',
    years: '331-330 BC',
    color: '#b07848',
    summary: 'Gaugamela, the imperial capitals, and the symbolic end of Achaemenid power.',
  },
  eastIndia: {
    label: 'East and India',
    years: '329-326 BC',
    color: '#5e8b4f',
    summary: 'Bactria, Sogdiana, and the final eastward push into the Indus world.',
  },
  returnDeath: {
    label: 'Return and Death',
    years: '325-323 BC',
    color: '#8c5b5b',
    summary: "The hard return west, army crisis, and Alexander's death at Babylon.",
  },
};

const ALEXANDER_STOPS = [
  {
    id: 'pella',
    pleiades: 491687,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/491687' }],
    name: 'Pella',
    modern: 'Pella, Greece',
    lat: 40.761,
    lng: 22.519,
    year: -356,
    year_label: '356 BC',
    phase: 'macedon',
    type: 'origin',
    certainty: 'secure',
    desc: 'Alexander is born at Pella in 356 BC to Philip II and Olympias of Epirus. As a boy he tames the supposedly unrideable horse Bucephalus here, and at 13 begins three years of tutoring under Aristotle at nearby Mieza.',
    significance: "The court that raises him already commands the most formidable army in the Greek world; Alexander inherits both the throne and the Persian invasion Philip had been planning.",
    ancient_sources: ['Plutarch, Alexander 3'],
    source_note: '',
  },
  {
    id: 'aegae',
    name: 'Aegae',
    modern: 'Vergina, Greece',
    lat: 40.486,
    lng: 22.318,
    year: -336,
    year_label: '336 BC',
    phase: 'macedon',
    type: 'capital',
    certainty: 'secure',
    desc: 'Philip II is assassinated at Aegae in 336 BC by his own bodyguard Pausanias, cut down during the wedding festivities for his daughter. Alexander, 20 years old, moves immediately to secure the throne, eliminating rival claimants before the court can turn against him.',
    significance: "The lavish royal tombs excavated at Vergina in 1977, one believed to be Philip's own, still hold golden treasures that testify to the wealth and power Alexander inherited that day.",
    ancient_sources: ['Diodorus 16.91-94'],
    source_note: '',
  },
  {
    id: 'thebes',
    pleiades: 541138,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/541138' },
      { label: 'Livius', url: 'https://www.livius.org/articles/person/alexander-the-great/alexander-2.2/' },
    ],
    name: 'Thebes',
    modern: 'Thiva, Greece',
    lat: 38.320,
    lng: 23.318,
    year: -335,
    year_label: '335 BC',
    phase: 'macedon',
    type: 'siege',
    certainty: 'secure',
    desc: 'A false report of Alexander\'s death sparks a Theban revolt; he storms the city and razes it, sparing only the temples and the house of the poet Pindar.',
    significance: 'The destruction of Thebes terrifies the Greek states into acquiescence before Alexander leaves for Asia.',
    ancient_sources: ['Arrian 1.7-9', 'Diodorus 17.8-14'],
    source_note: '',
  },
  {
    id: 'amphipolis',
    pleiades: 501347,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/501347' }],
    name: 'Amphipolis',
    modern: 'Amfipoli, Greece',
    lat: 40.823,
    lng: 23.847,
    year: -334,
    year_label: '334 BC',
    phase: 'macedon',
    type: 'muster',
    certainty: 'secure',
    desc: "A strategic stronghold on the Strymon river fought over for a century — Athens lost it to Sparta's Brasidas in 424 BC, and Philip II seized it for Macedon in 357 BC. Alexander gathers his invasion force here in spring 334 BC before marching for the Hellespont.",
    significance: 'The colossal Kasta Tomb excavated nearby, crowned by a giant marble lion, dates to this era and shows how central the region remained to Macedonian power.',
    ancient_sources: ['Arrian 1.11'],
    source_note: '',
  },
  {
    id: 'hellespont-crossing',
    pleiades: 501434,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/501434' }],
    name: 'Hellespont Crossing',
    modern: 'Dardanelles, Turkey',
    lat: 40.205,
    lng: 26.405,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'crossing',
    certainty: 'approximate',
    desc: 'Alexander personally steers his flagship across the strait, and as it nears the Asian shore he hurls his spear into the beach, claiming the whole continent as territory won by the spear. Mid-channel he sacrifices a bull to Poseidon and pours a libation to the sea nymphs from a golden cup.',
    significance: "The crossing deliberately inverts Xerxes' invasion of Greece a century and a half earlier, recasting Alexander's war as Greek revenge carried back onto Persian soil.",
    ancient_sources: ['Arrian 1.11'],
    source_note: 'Marker represents the crossing zone, not an exact embarkation point.',
  },
  {
    id: 'ilion',
    pleiades: 550595,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/550595' }],
    name: 'Ilion / Troy',
    modern: 'Hisarlik, Turkey',
    lat: 39.957,
    lng: 26.239,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'ritual',
    certainty: 'secure',
    desc: "Alexander sacrifices at the tomb of Achilles and runs a ceremonial naked race around it with his companions, while Hephaestion performs the same rite at the tomb of Patroclus. He trades his own armor to Athena's temple for a shield reputed to date to the Trojan War, which his shield-bearer carries into every battle that follows.",
    significance: 'Alexander, who reportedly slept with a copy of the Iliad annotated by Aristotle under his pillow, is here casting himself explicitly as a second Achilles avenging Greece against Asia.',
    ancient_sources: ['Arrian 1.11-12'],
    source_note: '',
  },
  {
    id: 'granicus',
    links: [{ label: 'Livius', url: 'https://www.livius.org/articles/battle/granicus/' }],
    name: 'Granicus River',
    modern: 'Biga River, Turkey',
    lat: 40.263,
    lng: 27.193,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'battle',
    certainty: 'approximate',
    desc: "Charging across the river under a hail of javelins, Alexander is nearly killed when a Persian noble's blow shears the plume from his helmet; his companion Cleitus the Black saves his life by cutting off the attacker's arm just before the fatal strike lands. Afterward Alexander sends 300 suits of captured Persian armor to Athens with a pointed inscription crediting the victory to himself and 'the Greeks, except the Spartans.'",
    significance: 'It is his first battlefield test against a Persian army, and the near-death moment foreshadows a volatile bond with Cleitus, whom Alexander will kill with his own hands six years later in a drunken quarrel at Maracanda.',
    ancient_sources: ['Arrian 1.13-16'],
    source_note: 'Battlefield placement along the river is approximate.',
  },
  {
    id: 'sardis',
    pleiades: 550867,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/550867' }],
    name: 'Sardis',
    modern: 'Sart, Turkey',
    lat: 38.488,
    lng: 28.040,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'capital',
    certainty: 'secure',
    desc: "The Persian governor Mithrenes surrenders the citadel without a fight, handing Alexander the treasury of Lydia's old capital — the city where King Croesus once ruled and where, two centuries earlier, a Greek revolt against Persia had first been crushed. Alexander lets the Sardians keep their own laws while installing a Macedonian garrison, a light-touch pattern he repeats across Anatolia.",
    significance: "Taking the region's richest city intact, without a siege, gives Alexander both a war chest and proof that Persian rule in Asia Minor is more brittle than it looks.",
    ancient_sources: ['Arrian 1.17'],
    source_note: '',
  },
  {
    id: 'ephesus',
    pleiades: 599612,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/599612' }],
    name: 'Ephesus',
    modern: 'Selçuk, Turkey',
    lat: 37.941,
    lng: 27.341,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'city',
    certainty: 'secure',
    desc: 'After the Granicus, Alexander enters Ephesus, expels the Persian garrison and restores the democracy.',
    significance: 'Sets the template for his settlement of the Greek cities of Asia — liberator rather than new overlord.',
    ancient_sources: ['Arrian 1.17-18'],
    source_note: '',
  },
  {
    id: 'miletus',
    pleiades: 599799,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/599799' },
      { label: 'Livius', url: 'https://www.livius.org/articles/person/alexander-the-great/alexander-2.3/' },
    ],
    name: 'Miletus',
    modern: 'Balat, Turkey',
    lat: 37.530,
    lng: 27.278,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'siege',
    certainty: 'secure',
    desc: 'With a much larger Persian fleet anchored nearby at Mycale, Alexander makes the consequential decision to send home most of his own navy rather than risk a sea battle he could lose. His admiral Nicanor instead blocks the harbor mouth, and the city falls to a land assault while the Persian ships watch helplessly from open water.',
    significance: "The episode sets the campaign's naval doctrine: rather than fight Persia's superior fleet at sea, Alexander will strangle it by capturing every port and base it depends on.",
    ancient_sources: ['Arrian 1.18-19'],
    source_note: '',
  },
  {
    id: 'halicarnassus',
    pleiades: 461581651,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/461581651' },
      { label: 'Livius', url: 'https://www.livius.org/articles/battle/halicarnassus-334-bce/' },
    ],
    name: 'Halicarnassus',
    modern: 'Bodrum, Turkey',
    lat: 37.038,
    lng: 27.430,
    year: -334,
    year_label: '334 BC',
    phase: 'anatolia',
    type: 'siege',
    certainty: 'secure',
    desc: "Memnon of Rhodes, the single most capable commander in Persian service, organizes a fierce defense, including a night sortie that nearly burns Alexander's siege towers. When the lower city finally falls the garrison retreats to island citadels that hold out indefinitely, so Alexander leaves them blockaded and installs the exiled Carian queen Ada — who had adopted him as her son — as a loyal client ruler.",
    significance: "It is the costliest siege of the campaign so far and the last serious coastal resistance in western Anatolia before Alexander turns his army inland.",
    ancient_sources: ['Arrian 1.20-23'],
    source_note: '',
  },
  {
    id: 'gordium',
    pleiades: 609393,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/609393' }],
    name: 'Gordium',
    modern: 'Yassihoyuk, Turkey',
    lat: 39.654,
    lng: 31.999,
    year: -333,
    year_label: '333 BC',
    phase: 'anatolia',
    type: 'symbol',
    certainty: 'secure',
    desc: "In the old Phrygian capital, Alexander is shown an ancient wagon lashed with an impossibly tangled knot, tied — legend held — by the founder-king Gordius himself; whoever untied it was destined to rule Asia. Unable to find the ends, Alexander reportedly slices through it with his sword, or, in another ancient account, simply pulls out the pole-pin holding it together.",
    significance: 'True or embellished, the story spreads through the army as proof of destiny, and Gordium also serves as a winter halt where fresh Macedonian reinforcements rejoin the campaign.',
    ancient_sources: ['Arrian 2.3'],
    source_note: '',
  },
  {
    id: 'tarsus',
    pleiades: 648789,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/648789' }],
    name: 'Tarsus',
    modern: 'Tarsus, Turkey',
    lat: 36.917,
    lng: 34.895,
    year: -333,
    year_label: '333 BC',
    phase: 'anatolia',
    type: 'city',
    certainty: 'secure',
    desc: "After a scorching march through the Cilician Gates, Alexander plunges into the icy Cydnus river to bathe and is struck by a violent chill that nearly kills him. As his physician Philip prepares a drastic remedy, Alexander receives a letter warning that Philip has been bribed by Darius to poison him — and drinks the medicine anyway while handing Philip the letter, unread, in a calculated display of trust.",
    significance: 'The near-fatal illness, at the gateway from Anatolia into Syria, shows how close the whole campaign came to ending from something other than a Persian sword.',
    ancient_sources: ['Arrian 2.4'],
    source_note: '',
  },
  {
    id: 'issus',
    links: [{ label: 'Livius', url: 'https://www.livius.org/articles/battle/issus/' }],
    name: 'Issus',
    modern: 'near Dörtyol, Turkey',
    lat: 36.86,
    lng: 36.20,
    year: -333,
    year_label: '333 BC',
    phase: 'levantEgypt',
    type: 'battle',
    certainty: 'approximate',
    desc: "Darius III commands the battle in person on a cramped coastal plain that neutralizes his army's numerical advantage, and when the Macedonian line breaks through, the Great King abandons his chariot, shield, and royal cloak in his own flight. Alexander captures Darius's mother Sisygambis, wife Stateira, and children, and treats them with a courtesy that startles the Persian court.",
    significance: "News of the clash echoes for centuries — the Alexander Mosaic unearthed at Pompeii, showing Alexander driving straight at Darius's chariot, is a Roman copy of a Hellenistic painting made to commemorate this exact moment.",
    ancient_sources: ['Arrian 2.6-12'],
    source_note: 'The exact battlefield and river identification are debated.',
  },
  {
    id: 'damascus',
    pleiades: 678106,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/678106' }],
    name: 'Damascus',
    modern: 'Damascus, Syria',
    lat: 33.512,
    lng: 36.309,
    year: -333,
    year_label: '333 BC',
    phase: 'levantEgypt',
    type: 'city',
    certainty: 'secure',
    desc: 'After Issus, Parmenion secures Damascus — and with it Darius\'s war-chest, baggage train, and many captured Persian noncombatants and envoys.',
    significance: 'The captured treasury helps fund the campaign as Alexander turns down the Levantine coast.',
    ancient_sources: ['Arrian 2.11', 'Curtius 3.12-13'],
    source_note: '',
  },
  {
    id: 'tyre',
    pleiades: 678437,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/678437' },
      { label: 'Livius', url: 'https://www.livius.org/articles/battle/tyre-332-bce/' },
    ],
    name: 'Tyre',
    modern: 'Sour, Lebanon',
    lat: 33.270,
    lng: 35.204,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'siege',
    certainty: 'secure',
    desc: "Tyre refuses Alexander entry to sacrifice at its temple of Melqart, and the standoff triggers a seven-month siege in which his engineers build a stone-and-timber mole out to the island city — a causeway so massive that, silted over by centuries of sand, it has permanently joined Tyre to the mainland ever since. When the walls finally fall, several thousand Tyrians are killed and some 30,000 survivors are sold into slavery.",
    significance: "It is the hardest siege of the entire campaign and permanently reshapes the Lebanese coastline; the mole Alexander's engineers built 2,300 years ago is why Tyre is a peninsula today rather than an island.",
    ancient_sources: ['Arrian 2.15-24'],
    source_note: '',
  },
  {
    id: 'gaza',
    pleiades: 687902,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/687902' },
      { label: 'Livius', url: 'https://www.livius.org/articles/person/alexander-the-great/alexander-2.7/' },
    ],
    name: 'Gaza',
    modern: 'Gaza',
    lat: 31.505,
    lng: 34.462,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'siege',
    certainty: 'approximate',
    desc: "The eunuch commander Batis holds Gaza for Darius through a grueling two-month siege, built on a raised mound that forces Alexander's engineers to construct earthwork ramps around the entire circuit of walls; Alexander himself is wounded twice, once seriously in the shoulder. One disputed ancient account claims that after the city fell, Alexander had the defiant Batis dragged behind a chariot around the walls, deliberately echoing Achilles's treatment of Hector at Troy.",
    significance: "As the last fortified position between the Levant and the Nile, Gaza's fall opens Egypt to Alexander without another battle — the Persian satrap there surrenders on his arrival rather than risk a fight.",
    ancient_sources: ['Arrian 2.25-27'],
    source_note: 'Marker indicates the ancient city area in a heavily transformed modern urban landscape.',
  },
  {
    id: 'memphis',
    pleiades: 736963,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/736963' }],
    name: 'Memphis',
    modern: 'Mit Rahina, Egypt',
    lat: 29.849,
    lng: 31.254,
    year: -332,
    year_label: '332 BC',
    phase: 'levantEgypt',
    type: 'capital',
    certainty: 'secure',
    desc: "Egypt, chafing under harsh Persian rule, welcomes Alexander as a liberator; at Memphis he is crowned Pharaoh in the traditional rites and sacrifices to the sacred Apis bull, a pointed contrast with Persian rulers remembered for insulting Egyptian religion. He splits civil, military, and financial authority among separate officials rather than appointing one all-powerful satrap.",
    significance: "The unusual power-sharing arrangement reflects Egypt's wealth and strategic importance — this is a province Alexander cannot afford to let one ambitious governor turn into an independent kingdom.",
    ancient_sources: ['Arrian 3.1'],
    source_note: '',
  },
  {
    id: 'alexandria-egypt',
    pleiades: 727070,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/727070' }],
    name: 'Alexandria',
    modern: 'Alexandria, Egypt',
    lat: 31.200,
    lng: 29.918,
    year: -331,
    year_label: '331 BC',
    phase: 'levantEgypt',
    type: 'foundation',
    certainty: 'secure',
    desc: "Alexander personally selects the site, a strip of land between the sea and Lake Mareotis near the fishing village of Rhakotis, and has his architect Dinocrates lay out its street grid — reportedly marking the plan in barley meal when chalk ran out, an omen his seer Aristander read as proof the city would feed many nations. Alexander leaves within weeks and never sees the city that will carry his name into history.",
    significance: "Of the roughly twenty cities named Alexandria that he founds across his empire, this is the only one to become a major world city — later home to the Pharos lighthouse, the Great Library, and Cleopatra's Egypt.",
    ancient_sources: ['Arrian 3.1-2'],
    source_note: '',
  },
  {
    id: 'siwa',
    pleiades: 716520,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/716520' }],
    name: 'Siwa Oasis',
    modern: 'Siwa, Egypt',
    lat: 29.204,
    lng: 25.519,
    year: -331,
    year_label: '331 BC',
    phase: 'levantEgypt',
    type: 'oracle',
    certainty: 'secure',
    desc: "The desert crossing to Siwa is gruelling and, by ancient accounts, nearly fatal — a sandstorm strands the party until ravens, or in another version talking snakes, guide them back onto the path. Alexander meets the oracle's priest alone, and though he never discloses what was asked or answered, rumor immediately spreads that the god Ammon has confirmed him as his son.",
    significance: "The ambiguity is strategically useful: without formally claiming divinity, Alexander lets the story of divine sonship circulate through the army and the wider Greek world for the rest of his life.",
    ancient_sources: ['Arrian 3.3-4', 'Plutarch, Alexander 27'],
    source_note: '',
  },
  {
    id: 'gaugamela',
    links: [{ label: 'Livius', url: 'https://www.livius.org/articles/battle/gaugamela-331-bce/' }],
    name: 'Gaugamela',
    modern: 'near Mosul, Iraq',
    lat: 36.360,
    lng: 43.250,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'battle',
    certainty: 'disputed',
    desc: "Darius levels the plain near Gaugamela himself to give his scythed chariots and war elephants — the first Alexander's army has ever faced — open ground to work, fielding a force ancient sources swell to hundreds of thousands against Alexander's roughly 47,000. When Parmenion urges a night attack to exploit surprise, Alexander refuses, saying he will not steal a victory; instead he draws the Persian cavalry out of position and drives his Companions straight through the gap at Darius, who flees the field a second and final time.",
    significance: "With Darius's authority shattered beyond recovery, the battle effectively ends organized Achaemenid resistance and hands Alexander the wealthiest cities of the empire without further major fighting.",
    ancient_sources: ['Arrian 3.8-15'],
    source_note: 'The battlefield location is approximate and debated.',
  },
  {
    id: 'babylon-entry',
    pleiades: 653377582,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/653377582' }],
    name: 'Babylon',
    modern: 'Hillah, Iraq',
    lat: 32.542,
    lng: 44.421,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: "Babylon's satrap Mazaeus surrenders the city without a fight, and Alexander enters along a road strewn with flowers and incense to a population that had chafed under Persian governors. He sacrifices to the Babylonian god Marduk and orders the temples Xerxes had destroyed generations earlier rebuilt, then lets his exhausted army rest here for more than a month.",
    significance: 'Babylon becomes his favored administrative capital for the rest of the campaign, and it is here — a decade later, almost to the location — that Alexander will die.',
    ancient_sources: ['Arrian 3.16'],
    source_note: '',
  },
  {
    id: 'susa',
    pleiades: 912936,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/912936' }],
    name: 'Susa',
    modern: 'Shush, Iran',
    lat: 32.189,
    lng: 48.257,
    year: -331,
    year_label: '331 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: "Susa's treasury yields one of history's great hauls of captured wealth — ancient sources put it near 40,000 to 50,000 talents of gold and silver. When Alexander sits on Darius's throne his feet don't reach the footstool, and when a page slides a table underneath instead, one of Darius's former courtiers bursts into tears at seeing the Great King's furniture used this way; Alexander is struck enough by the moment that he nearly has the boy punished for weeping.",
    significance: 'Control of the Persian treasury turns the campaign from a raid into a durable empire — Alexander can now pay, feed, and reward an army indefinitely.',
    ancient_sources: ['Arrian 3.16'],
    source_note: '',
  },
  {
    id: 'persian-gate',
    links: [{ label: 'Livius', url: 'https://www.livius.org/articles/battle/persian-gate-330-bce/' }],
    name: 'Persian Gate',
    modern: 'Zagros Mountains, Iran',
    lat: 30.72,
    lng: 51.55,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'battle',
    certainty: 'approximate',
    desc: "The Persian noble Ariobarzanes, commanding a force far smaller than Alexander's, blocks the mountain pass into Persis for roughly a month and inflicts serious casualties in a direct assault — an eerie echo of Thermopylae, this time with Alexander's own army pinned at the narrows. A captured shepherd finally reveals a mountain track around the position, and a night flanking march lets Alexander break the defense from behind.",
    significance: "It is a rare tactical setback in the campaign and proves that Gaugamela's political collapse of the Persian empire did not end determined local resistance.",
    ancient_sources: ['Arrian 3.18'],
    source_note: 'Marker is a generalized location for the mountain pass battle.',
  },
  {
    id: 'persepolis',
    pleiades: 922695,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/922695' }],
    name: 'Persepolis',
    modern: 'Marvdasht, Iran',
    lat: 29.935,
    lng: 52.891,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: "Alexander lets his army sack Persepolis with a severity harsher than any other captured city, and its treasury is reportedly carried off on thousands of pack animals and camels. Months later, at a drunken banquet, the Athenian courtesan Thais is said to have urged the burning of Xerxes's palace in revenge for his burning of Athens 150 years before, and Alexander joins in setting the torch himself.",
    significance: "Ancient historians already argued over whether the burning was calculated propaganda or a regretted impulse, but either way it symbolically closes the account opened when Persia burned Athens's temples in 480 BC.",
    ancient_sources: ['Arrian 3.18', 'Diodorus 17.70-72'],
    source_note: '',
  },
  {
    id: 'ecbatana',
    pleiades: 903021,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/903021' }],
    name: 'Ecbatana',
    modern: 'Hamadan, Iran',
    lat: 34.799,
    lng: 48.514,
    year: -330,
    year_label: '330 BC',
    phase: 'persianCore',
    type: 'capital',
    certainty: 'secure',
    desc: "Here Alexander formally discharges the Greek allied contingents of the League of Corinth, declaring the panhellenic war of revenge against Persia officially finished — everything that follows is now his personal war. He leaves the aging general Parmenion in Ecbatana guarding the treasury and the rear, a posting that ends with Parmenion's execution the following year after his son Philotas is convicted of conspiracy.",
    significance: 'The formal dismissal marks the moment the campaign stops being a Greek coalition war and becomes an open-ended Macedonian conquest with no fixed endpoint.',
    ancient_sources: ['Arrian 3.19'],
    source_note: '',
  },
  {
    id: 'bactra',
    pleiades: 961886,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/961886' }],
    name: 'Bactra',
    modern: 'Balkh, Afghanistan',
    lat: 36.758,
    lng: 66.898,
    year: -329,
    year_label: '329 BC',
    phase: 'eastIndia',
    type: 'capital',
    certainty: 'secure',
    desc: "Bactra becomes Alexander's base for hunting down Bessus, the satrap who murdered Darius and proclaimed himself the new Great King; Bessus is eventually captured, ritually mutilated in the Persian manner reserved for usurpers, and executed. From here Alexander also fights a grinding two-year guerrilla war against local warlords, most stubbornly Spitamenes, in terrain far harder than the Persian army ever presented.",
    significance: 'The Bactrian and Sogdian campaigns cost Alexander more time and casualties than conquering the entire Persian heartland, marking his shift from conquering an empire to occupying one against constant local resistance.',
    ancient_sources: ['Arrian 3.28-29'],
    source_note: '',
  },
  {
    id: 'maracanda',
    pleiades: 59915,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/59915' },
      { label: 'Livius', url: 'https://www.livius.org/articles/place/maracanda/' },
    ],
    name: 'Maracanda',
    modern: 'Samarkand, Uzbekistan',
    lat: 39.656,
    lng: 66.947,
    year: -329,
    year_label: '329 BC',
    phase: 'eastIndia',
    type: 'city',
    certainty: 'secure',
    desc: 'The Sogdian capital (modern Samarkand) becomes a base for the northeastern campaigns; here in 328 Alexander kills his officer Cleitus the Black in a drunken quarrel.',
    significance: 'Marks the mounting strain of the eastern war on Alexander and his court.',
    ancient_sources: ['Arrian 3.30', 'Arrian 4.8-9'],
    source_note: '',
  },
  {
    id: 'sogdian-rock',
    links: [{ label: 'Livius', url: 'https://www.livius.org/sources/content/arrian/anabasis/alexander-captures-the-sogdian-rock/' }],
    name: 'Sogdian Rock',
    modern: 'Sogdiana, Uzbekistan/Tajikistan region',
    lat: 38.55,
    lng: 67.00,
    year: -327,
    year_label: '327 BC',
    phase: 'eastIndia',
    type: 'siege',
    certainty: 'disputed',
    desc: "When the defenders mock Alexander to find soldiers with wings to reach their supposedly unclimbable summit, he recruits about 300 volunteer mountaineers who scale the cliff face at night using tent pegs and ropes, appearing above the fortress at dawn; the stunned garrison surrenders without a fight. Among the captives is Roxane, daughter of the local nobleman Oxyartes, whom Alexander marries shortly after.",
    significance: "The marriage to a non-Greek noblewoman, the first of his three wives, signals Alexander's growing willingness to bind conquered elites to him through kinship rather than force alone.",
    ancient_sources: ['Arrian 4.18-19'],
    source_note: 'The exact location of the Sogdian Rock is disputed; marker is regional.',
  },
  {
    id: 'taxila',
    pleiades: 60083,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/60083' }],
    name: 'Taxila',
    modern: 'Taxila, Pakistan',
    lat: 33.746,
    lng: 72.839,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'city',
    certainty: 'secure',
    desc: "King Ambhi of Taxila submits to Alexander without a fight, seeking Macedonian help against his rival Porus across the Hydaspes, and gifts him war elephants and troops. Here Alexander's philosophers famously debate a group of Indian ascetics the Greeks call 'gymnosophists' — naked wise men — and one of them, Calanus, joins the march west and later ends his own life on a funeral pyre at Susa rather than face old age.",
    significance: 'Taxila shows conquest by alliance rather than battle at the eastern edge of the known world, and the encounter with Indian philosophy leaves a lasting mark on the Greek image of India as a land of wisdom.',
    ancient_sources: ['Arrian 5.3-8'],
    source_note: '',
  },
  {
    id: 'aornos',
    pleiades: 59687,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/59687' },
      { label: 'Livius', url: 'https://www.livius.org/articles/battle/aornus/' },
    ],
    name: 'Aornos',
    modern: 'Pir-Sar, Pakistan',
    lat: 34.722,
    lng: 73.285,
    year: -326,
    year_label: '327-326 BC',
    phase: 'eastIndia',
    type: 'siege',
    certainty: 'approximate',
    desc: 'Alexander storms the great rock fortress of Aornos, which local legend held even Heracles had failed to take.',
    significance: 'The last major siege before India, burnishing the Heraclean myth around Alexander.',
    ancient_sources: ['Arrian 4.28-30'],
    source_note: 'Usually identified with Pir-Sar / Una west of the Indus; the exact site is debated.',
  },
  {
    id: 'hydaspes',
    pleiades: 59837,
    links: [
      { label: 'Pleiades', url: 'https://pleiades.stoa.org/places/59837' },
      { label: 'Livius', url: 'https://www.livius.org/articles/battle/hydaspes/' },
    ],
    name: 'Hydaspes',
    modern: 'Jhelum River, Pakistan',
    lat: 32.93,
    lng: 73.73,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'battle',
    certainty: 'approximate',
    desc: "Porus fields roughly 200 war elephants, the largest force Alexander's army has ever faced, and Alexander crosses the flooded river at night during a thunderstorm miles upstream to outflank him while a decoy force under Craterus holds the main crossing. Porus, wounded and his army broken, keeps fighting from his elephant until surrender is the only option; asked how he wishes to be treated, he answers simply 'like a king,' and an impressed Alexander reinstates him with an even larger kingdom.",
    significance: 'Alexander founds two cities on the battlefield, Nicaea for the victory and Bucephala for his horse Bucephalus, who dies here — the last great pitched battle Alexander will ever fight.',
    photo_caption: 'Pictured: the Hydaspes (Jhelum) river',
    ancient_sources: ['Arrian 5.9-19'],
    source_note: 'Battlefield placement along the Jhelum/Hydaspes is approximate.',
  },
  {
    id: 'hyphasis',
    pleiades: 59839,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/59839' }],
    name: 'Hyphasis',
    modern: 'Beas River, India',
    lat: 31.82,
    lng: 75.12,
    year: -326,
    year_label: '326 BC',
    phase: 'eastIndia',
    type: 'turning-point',
    certainty: 'approximate',
    desc: 'After eight years of campaigning and seventy days of relentless monsoon rain, the army balks at rumors of an even larger kingdom ahead — the Nanda Empire, reportedly fielding thousands more war elephants than Porus had. The officer Coenus speaks for the exhausted troops, and Alexander sulks alone in his tent for three days before sacrificing for a river crossing that the omens conveniently declare unfavorable, giving him a face-saving reason to turn back.',
    significance: 'Before withdrawing, he raises twelve oversized altars to the Olympian gods marking the farthest edge of the march — the only time in his career Alexander is stopped by his own men rather than an enemy.',
    photo_caption: 'Pictured: the Hyphasis (Beas) river',
    ancient_sources: ['Arrian 5.25-29'],
    source_note: 'Marker represents the Beas/Hyphasis turnback zone.',
  },
  {
    id: 'patala',
    pleiades: 59987,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/59987' }],
    name: 'Patala',
    modern: 'Indus delta, Pakistan',
    lat: 24.722,
    lng: 68.065,
    year: -325,
    year_label: '325 BC',
    phase: 'returnDeath',
    type: 'city',
    certainty: 'approximate',
    desc: 'At the head of the Indus delta Alexander builds a harbour and divides his forces: Nearchus takes the fleet by sea while the army marches west.',
    significance: 'The launch point for the fleet\'s ocean voyage and the overland Gedrosian return.',
    ancient_sources: ['Arrian 6.17-20'],
    source_note: 'The ancient site has shifted with the Indus; location is approximate.',
  },
  {
    id: 'gedrosian-route',
    name: 'Gedrosian Route',
    modern: 'Makran / Balochistan',
    lat: 26.3,
    lng: 64.0,
    year: -325,
    year_label: '325 BC',
    phase: 'returnDeath',
    type: 'march',
    certainty: 'uncertain',
    desc: "Alexander reportedly chooses the brutal Gedrosian route partly to succeed where legend said even Cyrus the Great and Queen Semiramis had lost their armies; a flash flood one night alone kills a large number of camp followers, and starvation and heat exhaustion cost the army losses ancient writers count among the campaign's worst disasters. When a soldier brings him a helmet of scavenged water, Alexander, refusing to drink while his men go thirsty, pours it out on the sand in front of the whole column.",
    significance: "Meanwhile Nearchus's fleet, launched from Patala, suffers its own separate ordeal of storms and starvation along the coast, and the two forces don't fully reunite until the march finally reaches Persis.",
    ancient_sources: ['Arrian 6.22-27'],
    source_note: 'Marker and route are highly generalized; the exact march path is debated.',
  },
  {
    id: 'pasargadae',
    pleiades: 922693,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/922693' }],
    name: 'Pasargadae',
    modern: 'near Saadat Shahr, Iran',
    lat: 30.194,
    lng: 53.179,
    year: -324,
    year_label: '324 BC',
    phase: 'returnDeath',
    type: 'royal-site',
    certainty: 'secure',
    desc: 'Alexander finds the tomb of Cyrus the Great looted and desecrated, and — holding Cyrus in genuine reverence from his education in the Cyropaedia — orders it repaired, its guardian priests punished for the lapse, and its furnishings restored as closely as possible to their original description.',
    significance: "The gesture is calculated as much as sincere: publicly honoring the Achaemenid dynasty's founder helps Alexander present himself as Persia's rightful heir rather than merely its conqueror.",
    ancient_sources: ['Arrian 6.29'],
    source_note: '',
  },
  {
    id: 'opis',
    name: 'Opis',
    modern: 'near Baghdad, Iraq',
    lat: 33.45,
    lng: 44.65,
    year: -324,
    year_label: '324 BC',
    phase: 'returnDeath',
    type: 'mutiny',
    certainty: 'approximate',
    desc: "When Alexander announces he will send home his veteran Macedonian soldiers and fold 30,000 Persian-trained youths into the army in their place, the troops mutiny, mocking his claims of divine parentage and demanding all of them be discharged. Alexander has the ringleaders seized and executed on the spot, then delivers a blistering speech reminding the army everything they have gained under him — the standoff only breaks when the men, in tears, beg forgiveness and Alexander holds a mass reconciliation banquet for nine thousand.",
    significance: "The mutiny exposes how strained the army has become after nearly a decade of campaigning and how uneasy ordinary Macedonians are with Alexander's growing embrace of Persian customs and manpower.",
    ancient_sources: ['Arrian 7.8-12'],
    source_note: 'The exact location of ancient Opis is uncertain.',
  },
  {
    id: 'babylon-death',
    pleiades: 653377582,
    links: [{ label: 'Pleiades', url: 'https://pleiades.stoa.org/places/653377582' }],
    name: 'Babylon - Death of Alexander',
    modern: 'Hillah, Iraq',
    lat: 32.542,
    lng: 44.421,
    year: -323,
    year_label: '323 BC',
    phase: 'returnDeath',
    type: 'death',
    certainty: 'secure',
    desc: "Alexander falls ill after a long banquet at the house of his companion Medius and, according to the court's own Royal Diary, sickens and dies over roughly twelve days, unable to speak by the end. Asked on his deathbed to whom he leaves his empire, he is said to have answered only 'to the strongest' — or, by other accounts, said nothing at all — leaving no named heir behind.",
    significance: 'The silence detonates four decades of war among his generals, the Wars of the Successors, which carve his conquests into rival Hellenistic kingdoms; his own body is hijacked en route to Macedon by Ptolemy, who diverts it to Egypt, where its final resting place remains unknown to this day.',
    ancient_sources: ['Arrian 7.24-27', 'Plutarch, Alexander 75-77'],
    source_note: '',
  },
];

const ALEXANDER_ROUTES = [
  { id: 'pella-aegae-amphipolis', from: 'pella', to: 'amphipolis', phase: 'macedon', certainty: 'reconstructed', label: 'Macedonian base route', coords: [[22.519, 40.761], [22.318, 40.486], [23.847, 40.823]], source_note: 'Narrative connector between Macedonian royal centers and the eastward staging area.' },
  { id: 'amphipolis-hellespont', from: 'amphipolis', to: 'hellespont-crossing', phase: 'anatolia', certainty: 'reconstructed', label: 'Toward the Hellespont', coords: [[23.847, 40.823], [24.40, 40.86], [25.55, 40.45], [26.405, 40.205]], source_note: 'Generalized overland approach to the crossing.' },
  { id: 'hellespont-granicus-sardis', from: 'hellespont-crossing', to: 'sardis', phase: 'anatolia', certainty: 'reconstructed', label: 'Opening of Asia Minor', coords: [[26.405, 40.205], [26.239, 39.957], [27.193, 40.263], [28.040, 38.488]], source_note: 'Generalized route through northwest Anatolia after the crossing.' },
  { id: 'sardis-coast-halicar-gordium', from: 'sardis', to: 'gordium', phase: 'anatolia', certainty: 'reconstructed', label: 'Coastal sieges and inland turn', coords: [[28.040, 38.488], [27.278, 37.530], [27.430, 37.038], [30.70, 37.75], [31.999, 39.654]], source_note: 'Simplifies a campaign sequence with coastal and inland movements.' },
  { id: 'gordium-tarsus-issus', from: 'gordium', to: 'issus', phase: 'anatolia', certainty: 'reconstructed', label: 'Through Cilicia to Issus', coords: [[31.999, 39.654], [33.00, 38.60], [34.895, 36.917], [36.20, 36.86]], source_note: 'Generalized movement from central Anatolia through Cilicia.' },
  { id: 'issus-tyre-gaza', from: 'issus', to: 'gaza', phase: 'levantEgypt', certainty: 'reconstructed', label: 'Down the Levantine coast', coords: [[36.20, 36.86], [35.90, 35.50], [35.52, 34.45], [35.204, 33.270], [34.462, 31.505]], source_note: 'Narrative coastal connector, not a surveyed itinerary.' },
  { id: 'gaza-memphis-alexandria-siwa', from: 'gaza', to: 'siwa', phase: 'levantEgypt', certainty: 'reconstructed', label: 'Egypt and the oracle', coords: [[34.462, 31.505], [31.254, 29.849], [29.918, 31.200], [27.50, 30.50], [25.519, 29.204]], source_note: 'Generalized Egyptian route, including the desert journey to Siwa.' },
  { id: 'egypt-gaugamela-babylon', from: 'siwa', to: 'babylon-entry', phase: 'persianCore', certainty: 'reconstructed', label: 'Return east to Gaugamela and Babylon', coords: [[25.519, 29.204], [29.918, 31.200], [34.462, 31.505], [36.20, 36.86], [43.250, 36.360], [44.421, 32.542]], source_note: 'Compresses the return from Egypt and the march to Gaugamela into a narrative connector.' },
  { id: 'babylon-susa-persepolis-ecbatana', from: 'babylon-entry', to: 'ecbatana', phase: 'persianCore', certainty: 'reconstructed', label: 'Imperial capitals', coords: [[44.421, 32.542], [48.257, 32.189], [51.55, 30.72], [52.891, 29.935], [48.514, 34.799]], source_note: 'Generalized route across the Persian imperial core.' },
  { id: 'ecbatana-bactra-sogdian', from: 'ecbatana', to: 'sogdian-rock', phase: 'eastIndia', certainty: 'uncertain', label: 'Pursuit and eastern campaigns', coords: [[48.514, 34.799], [54.35, 36.70], [61.20, 36.70], [66.898, 36.758], [67.00, 38.55]], source_note: 'Highly simplified eastward route; many exact movements are omitted.' },
  { id: 'sogdian-taxila-hydaspes-hyphasis', from: 'sogdian-rock', to: 'hyphasis', phase: 'eastIndia', certainty: 'reconstructed', label: 'Into the Indus world', coords: [[67.00, 38.55], [69.20, 34.55], [72.839, 33.746], [73.73, 32.93], [75.12, 31.82]], source_note: 'Generalized connector from Central Asia into the Punjab.' },
  { id: 'hyphasis-gedrosia-pasargadae-opis-babylon', from: 'hyphasis', to: 'babylon-death', phase: 'returnDeath', certainty: 'uncertain', label: 'Return west', coords: [[75.12, 31.82], [68.35, 25.40], [64.0, 26.3], [58.0, 27.5], [53.179, 30.194], [44.65, 33.45], [44.421, 32.542]], source_note: 'The Gedrosian return is deliberately generalized and should be shown as uncertain.' },
];
