// AUTO-GENERATED by scripts/build-alexander-photos.mjs — do not hand-edit.
// Hero photos for Alexander campaign stops, from Wikidata P18 → Wikimedia
// Commons, plus curated Commons pins. Each carries a thumbnail + attribution (Commons
// images are individually licensed — the panel shows credit + license).
window.ALEXANDER_PHOTOS = {
  "59687": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Hazara-Region_in_Pakistan_von_James_Abbott.jpg/960px-Hazara-Region_in_Pakistan_von_James_Abbott.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Hazara-Region_in_Pakistan_von_James_Abbott.jpg",
    "credit": "James Abbott (1807-1896)",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Hazara-Region_in_Pakistan_von_James_Abbott.jpg"
  },
  "59837": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Jhelum_River-Pakistan.jpg/960px-Jhelum_River-Pakistan.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Jhelum_River-Pakistan.jpg",
    "credit": "Myasinilyas",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Jhelum_River-Pakistan.jpg"
  },
  "59839": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Beasmanikant.jpg/960px-Beasmanikant.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/7/75/Beasmanikant.jpg",
    "credit": "Achiwiki356 at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Beasmanikant.jpg"
  },
  "59915": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Sherdor_madrasah_3.jpg/960px-Sherdor_madrasah_3.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Sherdor_madrasah_3.jpg",
    "credit": "Adam Harangozó",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sherdor_madrasah_3.jpg"
  },
  "59987": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Indus_River_Delta.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Indus_River_Delta.jpg",
    "credit": "NASA",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Indus_River_Delta.jpg",
    "position": "center 50%",
    "caption": "Pictured: Indus delta; Patala location approximate"
  },
  "60083": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Double-Headed_Eagle_Stupa_at_Sirkap_08.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Double-Headed_Eagle_Stupa_at_Sirkap_08.jpg",
    "credit": "Wikimedia Commons",
    "license": "CC BY-SA 1.0",
    "source": "https://commons.wikimedia.org/wiki/File:Double-Headed_Eagle_Stupa_at_Sirkap_08.jpg"
  },
  "491687": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/7/78/Pella_House_atrium.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/7/78/Pella_House_atrium.jpg",
    "credit": "Brian Donovan",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Pella_House_atrium.jpg"
  },
  "501347": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Liontari_of_Amphipolis.jpg/960px-Liontari_of_Amphipolis.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Liontari_of_Amphipolis.jpg",
    "credit": "Vlahos Vaggelis",
    "license": "CC BY 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Liontari_of_Amphipolis.jpg"
  },
  "501434": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Dardanelles_landsat.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Dardanelles_landsat.jpg",
    "credit": "NASA",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Dardanelles_landsat.jpg"
  },
  "541138": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Thebes-1.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Thebes-1.jpg",
    "credit": "J. Matthew Harrington",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Thebes-1.jpg"
  },
  "550595": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Troy1.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Troy1.jpg",
    "credit": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Troy1.jpg"
  },
  "550867": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/The_Bath-Gymnasium_complex_at_Sardis%2C_late_2nd_-_early_3rd_century_AD%2C_Sardis%2C_Turkey_%2817098680002%29.jpg/960px-The_Bath-Gymnasium_complex_at_Sardis%2C_late_2nd_-_early_3rd_century_AD%2C_Sardis%2C_Turkey_%2817098680002%29.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/e5/The_Bath-Gymnasium_complex_at_Sardis%2C_late_2nd_-_early_3rd_century_AD%2C_Sardis%2C_Turkey_%2817098680002%29.jpg",
    "credit": "Carole Raddato from FRANKFURT, Germany",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Bath-Gymnasium_complex_at_Sardis,_late_2nd_-_early_3rd_century_AD,_Sardis,_Turkey_(17098680002).jpg"
  },
  "599612": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Ephesus_-_Celsus_Library.jpg/960px-Ephesus_-_Celsus_Library.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Ephesus_-_Celsus_Library.jpg",
    "credit": "Bernard Gagnon",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ephesus_-_Celsus_Library.jpg"
  },
  "599799": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Theater_of_Miletus.jpg/960px-The_Theater_of_Miletus.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/5/5a/The_Theater_of_Miletus.jpg",
    "credit": "https://www.flickr.com/photos/jiuguangw/",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Theater_of_Miletus.jpg"
  },
  "609393": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ruins_of_Gordion_3.JPG/960px-Ruins_of_Gordion_3.JPG",
    "full": "https://upload.wikimedia.org/wikipedia/commons/3/32/Ruins_of_Gordion_3.JPG",
    "credit": "Stipich Béla",
    "license": "CC BY 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Ruins_of_Gordion_3.JPG"
  },
  "648789": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/8/83/Ulucami%2C_Tarsus%2C_Mersin_Province.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/8/83/Ulucami%2C_Tarsus%2C_Mersin_Province.jpg",
    "credit": "Nedim Ardoğa",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ulucami,_Tarsus,_Mersin_Province.jpg"
  },
  "678106": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Damascus_coll.jpg/960px-Damascus_coll.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Damascus_coll.jpg",
    "credit": "See above.",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Damascus_coll.jpg"
  },
  "678437": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Columns_at_Al_Mina_site%2C_Tyre%2C_Lebanon.jpg/960px-Columns_at_Al_Mina_site%2C_Tyre%2C_Lebanon.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Columns_at_Al_Mina_site%2C_Tyre%2C_Lebanon.jpg",
    "credit": "Vyacheslav Argenberg",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Columns_at_Al_Mina_site,_Tyre,_Lebanon.jpg"
  },
  "716520": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/5/58/SiwaAghurmiTemple.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/5/58/SiwaAghurmiTemple.jpg",
    "credit": "Roland Unger",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:SiwaAghurmiTemple.jpg"
  },
  "727070": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Alexandrie_Th%C3%A9%C3%A2tre_romain_2.jpg/960px-Alexandrie_Th%C3%A9%C3%A2tre_romain_2.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/d/db/Alexandrie_Th%C3%A9%C3%A2tre_romain_2.jpg",
    "credit": "Codex",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Alexandrie_Th%C3%A9%C3%A2tre_romain_2.jpg",
    "position": "center 45%"
  },
  "736963": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Memphis%2C_Ramses_II%2C_Ancient_Egypt.jpg/960px-Memphis%2C_Ramses_II%2C_Ancient_Egypt.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Memphis%2C_Ramses_II%2C_Ancient_Egypt.jpg",
    "credit": "Vyacheslav Argenberg",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Memphis,_Ramses_II,_Ancient_Egypt.jpg"
  },
  "903021": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/4/44/Rython_boz.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/4/44/Rython_boz.jpg",
    "credit": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Rython_boz.jpg"
  },
  "912936": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/The_Apadana%2C_a_large_hypostyle_room_of_36_columns_in_the_Palace_of_Darius%2C_Susa%2C_capital_of_Elam_and_of_the_Achaemenid_Empire%2C_Iran_%2846950284624%29.jpg/960px-The_Apadana%2C_a_large_hypostyle_room_of_36_columns_in_the_Palace_of_Darius%2C_Susa%2C_capital_of_Elam_and_of_the_Achaemenid_Empire%2C_Iran_%2846950284624%29.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/9/90/The_Apadana%2C_a_large_hypostyle_room_of_36_columns_in_the_Palace_of_Darius%2C_Susa%2C_capital_of_Elam_and_of_the_Achaemenid_Empire%2C_Iran_%2846950284624%29.jpg",
    "credit": "Carole Raddato from Frankfurt, Germany",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Apadana,_a_large_hypostyle_room_of_36_columns_in_the_Palace_of_Darius,_Susa,_capital_of_Elam_and_of_the_Achaemenid_Empire,_Iran_(46950284624).jpg"
  },
  "922693": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Cyrus_tomb.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Cyrus_tomb.jpg",
    "credit": "Behrad18n",
    "license": "Copyrighted free use",
    "source": "https://commons.wikimedia.org/wiki/File:Cyrus_tomb.jpg",
    "position": "center 42%"
  },
  "922695": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/%D9%BE%D8%A7%D9%86%D9%88%D8%B1%D8%A7%D9%85%D8%A7_%D8%B1%D9%88%D8%B2_%D8%AA%D8%AE%D8%AA_%D8%AC%D9%85%D8%B4%DB%8C%D8%AF.jpg/960px-%D9%BE%D8%A7%D9%86%D9%88%D8%B1%D8%A7%D9%85%D8%A7_%D8%B1%D9%88%D8%B2_%D8%AA%D8%AE%D8%AA_%D8%AC%D9%85%D8%B4%DB%8C%D8%AF.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/7/7b/%D9%BE%D8%A7%D9%86%D9%88%D8%B1%D8%A7%D9%85%D8%A7_%D8%B1%D9%88%D8%B2_%D8%AA%D8%AE%D8%AA_%D8%AC%D9%85%D8%B4%DB%8C%D8%AF.jpg",
    "credit": "Hamidhassas",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%D9%BE%D8%A7%D9%86%D9%88%D8%B1%D8%A7%D9%85%D8%A7_%D8%B1%D9%88%D8%B2_%D8%AA%D8%AE%D8%AA_%D8%AC%D9%85%D8%B4%DB%8C%D8%AF.jpg",
    "position": "center 55%"
  },
  "961886": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Green_Mosque%2C_Balkh.jpg/960px-Green_Mosque%2C_Balkh.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Green_Mosque%2C_Balkh.jpg",
    "credit": "AhmadElhan",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Green_Mosque,_Balkh.jpg",
    "position": "center 48%",
    "caption": "Pictured: later ruins at Balkh/Bactra"
  },
  "461581651": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_ruins_of_the_Mausoleum_at_Halicarnassus.jpg/960px-The_ruins_of_the_Mausoleum_at_Halicarnassus.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/f4/The_ruins_of_the_Mausoleum_at_Halicarnassus.jpg",
    "credit": "FollowingHadrian",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_ruins_of_the_Mausoleum_at_Halicarnassus.jpg"
  },
  "653377582": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Ishtar_Gate_at_Berlin_Museum.jpg/960px-Ishtar_Gate_at_Berlin_Museum.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Ishtar_Gate_at_Berlin_Museum.jpg",
    "credit": "Rictor Norton",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ishtar_Gate_at_Berlin_Museum.jpg"
  },
  "persian-gate": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/f/f6/2persian_gate_wall.JPG",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/f6/2persian_gate_wall.JPG",
    "credit": "Jona Lendering at English Wikipedia",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:2persian_gate_wall.JPG",
    "position": "center 50%",
    "caption": "Pictured: Persian Gate pass; battlefield marker is approximate"
  },
  "sogdian-rock": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Vista_de_les_muntanyes_al_sud_de_Mazori_Sharif_%28Panjakent%2C_Sughd%2C_Tajikistan%29.jpg/960px-Vista_de_les_muntanyes_al_sud_de_Mazori_Sharif_%28Panjakent%2C_Sughd%2C_Tajikistan%29.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Vista_de_les_muntanyes_al_sud_de_Mazori_Sharif_%28Panjakent%2C_Sughd%2C_Tajikistan%29.jpg",
    "credit": "Sorneguer",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Vista_de_les_muntanyes_al_sud_de_Mazori_Sharif_(Panjakent,_Sughd,_Tajikistan).jpg",
    "position": "center 52%",
    "caption": "Pictured: Sughd mountain landscape; exact site disputed"
  },
  "gedrosian-route": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Baluchistan_Canyons.jpg/960px-Baluchistan_Canyons.jpg",
    "full": "https://upload.wikimedia.org/wikipedia/commons/8/81/Baluchistan_Canyons.jpg",
    "credit": "Uzair189",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Baluchistan_Canyons.jpg",
    "position": "center 48%",
    "caption": "Pictured: Makran/Balochistan landscape; route generalized"
  },
  "opis": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/160731-D-PB383-021_Tigris_River_flows_through_Baghdad%2C_July_2016.JPG/960px-160731-D-PB383-021_Tigris_River_flows_through_Baghdad%2C_July_2016.JPG",
    "full": "https://upload.wikimedia.org/wikipedia/commons/f/fe/160731-D-PB383-021_Tigris_River_flows_through_Baghdad%2C_July_2016.JPG",
    "credit": "DoD photo by Navy Petty Officer 2nd Class Dominique A. Pineiro",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:160731-D-PB383-021_Tigris_River_flows_through_Baghdad,_July_2016.JPG",
    "position": "center 52%",
    "caption": "Pictured: Tigris near Baghdad; Opis location uncertain"
  }
};
