// AUTO-GENERATED by scripts/build-vici-links.mjs — do not hand-edit.
// Pleiades id → vici.org reference. Source content is CC BY-SA 3.0 (+CC0
// metadata) — NOT CC-BY-4.0; record license accordingly if ever reused.
// has_photo: true|false only when built with --photos, else null.
window.VICI_LINKS = {
  "50064": {
    "vici": "96663",
    "url": "https://vici.org/vici/96663/",
    "has_photo": null
  },
  "79409": {
    "vici": "3910",
    "url": "https://vici.org/vici/3910/",
    "has_photo": null
  },
  "79574": {
    "vici": "1484",
    "url": "https://vici.org/vici/1484/",
    "has_photo": null
  },
  "79696": {
    "vici": "35197",
    "url": "https://vici.org/vici/35197/",
    "has_photo": null
  },
  "128409": {
    "vici": "7270",
    "url": "https://vici.org/vici/7270/",
    "has_photo": null
  },
  "148142": {
    "vici": "2705",
    "url": "https://vici.org/vici/2705/",
    "has_photo": null
  },
  "148217": {
    "vici": "2707",
    "url": "https://vici.org/vici/2707/",
    "has_photo": null
  },
  "177659": {
    "vici": "16836",
    "url": "https://vici.org/vici/16836/",
    "has_photo": null
  },
  "187354": {
    "vici": "3106",
    "url": "https://vici.org/vici/3106/",
    "has_photo": null
  },
  "246410": {
    "vici": "10600",
    "url": "https://vici.org/vici/10600/",
    "has_photo": null
  },
  "295247": {
    "vici": "59901",
    "url": "https://vici.org/vici/59901/",
    "has_photo": null
  },
  "309552": {
    "vici": "31261",
    "url": "https://vici.org/vici/31261/",
    "has_photo": null
  },
  "315223": {
    "vici": "7850",
    "url": "https://vici.org/vici/7850/",
    "has_photo": null
  },
  "324835": {
    "vici": "2190",
    "url": "https://vici.org/vici/2190/",
    "has_photo": null
  },
  "344456": {
    "vici": "2446",
    "url": "https://vici.org/vici/2446/",
    "has_photo": null
  },
  "373778": {
    "vici": "2454",
    "url": "https://vici.org/vici/2454/",
    "has_photo": null
  },
  "375237": {
    "vici": "34646",
    "url": "https://vici.org/vici/34646/",
    "has_photo": null
  },
  "413331": {
    "vici": "18370",
    "url": "https://vici.org/vici/18370/",
    "has_photo": null
  },
  "423130": {
    "vici": "7199",
    "url": "https://vici.org/vici/7199/",
    "has_photo": null
  },
  "432886": {
    "vici": "1765",
    "url": "https://vici.org/vici/1765/",
    "has_photo": null
  },
  "433048": {
    "vici": "16438",
    "url": "https://vici.org/vici/16438/",
    "has_photo": null
  },
  "491526": {
    "vici": "2210",
    "url": "https://vici.org/vici/2210/",
    "has_photo": null
  },
  "501645": {
    "vici": "32614",
    "url": "https://vici.org/vici/32614/",
    "has_photo": null
  },
  "533032": {
    "vici": "71102",
    "url": "https://vici.org/vici/71102/",
    "has_photo": null
  },
  "550812": {
    "vici": "2290",
    "url": "https://vici.org/vici/2290/",
    "has_photo": null
  },
  "550927": {
    "vici": "88174",
    "url": "https://vici.org/vici/88174/",
    "has_photo": null
  },
  "570151": {
    "vici": "33599",
    "url": "https://vici.org/vici/33599/",
    "has_photo": null
  },
  "570711": {
    "vici": "25210",
    "url": "https://vici.org/vici/25210/",
    "has_photo": null
  },
  "579885": {
    "vici": "2124",
    "url": "https://vici.org/vici/2124/",
    "has_photo": null
  },
  "599490": {
    "vici": "26090",
    "url": "https://vici.org/vici/26090/",
    "has_photo": null
  },
  "599612": {
    "vici": "2278",
    "url": "https://vici.org/vici/2278/",
    "has_photo": null
  },
  "638783": {
    "vici": "7432",
    "url": "https://vici.org/vici/7432/",
    "has_photo": null
  },
  "638837": {
    "vici": "30714",
    "url": "https://vici.org/vici/30714/",
    "has_photo": null
  },
  "639072": {
    "vici": "68738",
    "url": "https://vici.org/vici/68738/",
    "has_photo": null
  },
  "648789": {
    "vici": "2316",
    "url": "https://vici.org/vici/2316/",
    "has_photo": null
  },
  "658465": {
    "vici": "2404",
    "url": "https://vici.org/vici/2404/",
    "has_photo": null
  },
  "678106": {
    "vici": "2506",
    "url": "https://vici.org/vici/2506/",
    "has_photo": null
  },
  "687828": {
    "vici": "25020",
    "url": "https://vici.org/vici/25020/",
    "has_photo": null
  },
  "697725": {
    "vici": "21417",
    "url": "https://vici.org/vici/21417/",
    "has_photo": null
  },
  "707555": {
    "vici": "17253",
    "url": "https://vici.org/vici/17253/",
    "has_photo": null
  },
  "1628988": {
    "vici": "40811",
    "url": "https://vici.org/vici/40811/",
    "has_photo": null
  },
  "132886213": {
    "vici": "15049",
    "url": "https://vici.org/vici/15049/",
    "has_photo": null
  },
  "143098101": {
    "vici": "23818",
    "url": "https://vici.org/vici/23818/",
    "has_photo": null
  },
  "155158534": {
    "vici": "17598",
    "url": "https://vici.org/vici/17598/",
    "has_photo": null
  },
  "607649583": {
    "vici": "11876",
    "url": "https://vici.org/vici/11876/",
    "has_photo": null
  },
  "643273747": {
    "vici": "80579",
    "url": "https://vici.org/vici/80579/",
    "has_photo": null
  },
  "676148653": {
    "vici": "18042",
    "url": "https://vici.org/vici/18042/",
    "has_photo": null
  },
  "680348962": {
    "vici": "36715",
    "url": "https://vici.org/vici/36715/",
    "has_photo": null
  },
  "703315102": {
    "vici": "42275",
    "url": "https://vici.org/vici/42275/",
    "has_photo": null
  },
  "711164401": {
    "vici": "58294",
    "url": "https://vici.org/vici/58294/",
    "has_photo": null
  },
  "814364493": {
    "vici": "31272",
    "url": "https://vici.org/vici/31272/",
    "has_photo": null
  },
  "848395608": {
    "vici": "58605",
    "url": "https://vici.org/vici/58605/",
    "has_photo": null
  },
  "877521473": {
    "vici": "24000",
    "url": "https://vici.org/vici/24000/",
    "has_photo": null
  },
  "929651744": {
    "vici": "17796",
    "url": "https://vici.org/vici/17796/",
    "has_photo": null
  }
};
