// ═══════════════════════════════════════════════════════════════════════════
//  build-pages.mjs — generate the Alexander page from the Roman index.html
//
//  The mode split ships as two focused pages on one origin:
//    • index.html                                  → Roman map (VIA_LOCK_MODE=roman)
//    • alexander-the-great-campaigns/index.html    → campaign (VIA_LOCK_MODE=alexander)
//
//  index.html is the single hand-edited source. This script reads it and emits the
//  Alexander sibling by rewriting three things (everything else — the whole body
//  scaffold — is shared verbatim, so there is no drift):
//    1. the VIA:LOCK block      → window.VIA_LOCK_MODE = 'alexander'
//    2. the VIA:HEADMETA block  → Alexander title / description / OG / Twitter
//    3. css/js asset paths      → prefixed with ../ (the page lives one dir down)
//
//  Run:  node scripts/build-pages.mjs      (after any edit to index.html)
//  Flags: --check  → fail (exit 1) if the generated file is stale, don't write
//         (useful in CI / a pre-commit guard).
// ═══════════════════════════════════════════════════════════════════════════
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC  = resolve(ROOT, 'index.html');
const OUT  = resolve(ROOT, 'alexander-the-great-campaigns', 'index.html');
const checkOnly = process.argv.includes('--check');

// Alexander per-page <head> metadata. Crawlers read static HTML (not JS), so the
// social-unfurl fields must be baked in per page here — they can't be set at runtime.
const ALEXANDER_HEADMETA = `  <meta name="description" content="Follow Alexander the Great's campaign across the ancient world — from Pella to the Hyphasis and back to Babylon, each stop anchored to the Pleiades gazetteer and the ancient historians.">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="VIA — Alexander's Campaign">
  <meta property="og:title" content="Alexander's Campaign — VIA">
  <meta property="og:description" content="Trace Alexander's route across the ancient world, stop by stop — battles, sieges, and founded cities, mapped honestly where scholars still dispute the ground.">
  <meta property="og:url" content="https://danielkorr.github.io/ancient-world-explorer/alexander-the-great-campaigns/">
  <meta property="og:image" content="https://danielkorr.github.io/ancient-world-explorer/alexander-the-great-campaigns/og-image.png?v=1">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Alexander's Campaign — VIA">
  <meta name="twitter:description" content="Trace Alexander's route across the ancient world, stop by stop — mapped honestly where scholars still dispute the ground.">
  <meta name="twitter:image" content="https://danielkorr.github.io/ancient-world-explorer/alexander-the-great-campaigns/og-image.png?v=1">
  <title>Alexander's Campaign — VIA</title>`;

// Replace the inner content between a <!-- MARK:START ... --> and <!-- MARK:END -->
// pair, keeping the marker comments so the block stays regenerable.
function replaceBlock(html, mark, innerHtml) {
  const re = new RegExp(`(<!-- VIA:${mark}:START[\\s\\S]*?-->)[\\s\\S]*?(<!-- VIA:${mark}:END -->)`);
  if (!re.test(html)) throw new Error(`marker VIA:${mark} not found in index.html`);
  return html.replace(re, `$1\n${innerHtml}\n  $2`);
}

function buildAlexander(src) {
  let html = src;
  // 1. Lock the page to the campaign mode.
  html = replaceBlock(html, 'LOCK', `  <script>window.VIA_LOCK_MODE = 'alexander';</script>`);
  // 2. Swap the social/head metadata.
  html = replaceBlock(html, 'HEADMETA', ALEXANDER_HEADMETA);
  // 3. This page lives one directory down, so local css/js resolve via ../ .
  //    Only rewrite root-relative css/ and js/ refs; CDN (https://) and the
  //    favicon data: URI are left alone, as are body cross-links (../, subfolder/).
  html = html.replace(/(\b(?:src|href)=")((?:css|js)\/)/g, '$1../$2');
  // 4. Stamp a GENERATED banner so nobody hand-edits the output.
  html = html.replace(/<!DOCTYPE html>/i,
    `<!DOCTYPE html>\n<!-- GENERATED by scripts/build-pages.mjs from ../index.html — DO NOT EDIT. -->`);
  return html;
}

const src = await readFile(SRC, 'utf8');
const out = buildAlexander(src);

if (checkOnly) {
  let current = '';
  try { current = await readFile(OUT, 'utf8'); } catch {}
  if (current !== out) {
    console.error('✗ alexander-the-great-campaigns/index.html is stale — run: node scripts/build-pages.mjs');
    process.exit(1);
  }
  console.log('✓ Alexander page is up to date.');
} else {
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, out, 'utf8');
  console.log(`✓ wrote ${OUT.replace(ROOT + '\\', '').replace(ROOT + '/', '')}`);
}
